version: '3'
services:
  db:
    environment:
      PGDATA: /var/lib/postgresql/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: time_manager_api_dev
      POSTGRES_HOST_AUTH_METHOD: trust
    image: 'postgres:12-alpine'
    restart: always
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
  server:
    build: "./time_manager_api"
    depends_on:
      - db
    environment:
      MIX_ENV: dev
    env_file:
      - .env
    ports:
      - '4000:4000'
    expose:
      - 4000
    volumes:
      - .:/app
  client_web:
    build: "./time_manager_client"
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      - default
    depends_on:
      - server
    environment:
      - PORT=8080
    restart: on-failure
    tty: true

networks:
  default:

volumes:
  pgdata:
