apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: client-web
  name: client-web
spec:
  containers:
  - env:
    - name: PORT
      value: "8080"
    image: client-web
    name: client-web
    ports:
    - containerPort: 8080
    resources: {}
    tty: true
  restartPolicy: OnFailure
status: {}
