name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # - name: Set up Elixir
    #   uses: actions/setup-elixir@v1
    #   with:
    #     elixir-version: '1.7'
    #     otp-version: '22.3'
    #
    # - name: Restore dependencies cache
    #   uses: actions/cache@v2
    #   with:
    #     path: time_manager_api/deps
    #     key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
    #     restore-keys: ${{ runner.os }}-mix-
    #
    # - name: Build
    #   run: docker-compose up -d

    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: 51.75.122.116
        username: timemanager
        password: timemanager
        port: 22
        source: "."
        target: "TimeManager"

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 51.75.122.116
        username: timemanager
        password: timemanager
        script: docker-compose up -d
