name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.7'
        otp-version: '22.3'
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Build
      run: docker-compose up -d

    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
          SSH_PRIVATE_KEY: >-"-----BEGIN RSA PRIVATE KEY-----
MIIJJwIBAAKCAgEA2zaeu2G0dHKCKJGTJVRcVzFn2D+rdmRhBQ9BihiNKmg+Qr0E
Lf3707NodfRx9JHIThuhpqgrMH5jdVdih7chiveFs2dBUutBw6kh5LZhpQ44WDDX
oGoVYMltMplMB7wQ+TZzdVNi6TK0SCy5ynyBXPNgnQ3Nq1FoGPQ4tiALcogrDwNf
OfFxM4vPa/VoZLJSNwvfxuXE5B5hkJvTqlcmMaH4v8LzaB3FTMlw4MkUQzDDpjfw
Kwv0/SU6t4S8J4k3Ex6zlG5MJrkfE80TgllVLr7l3pypA+gRIwvJSBBGct6yrk51
nlRDekPIGJSnS3zGjbWeBvCbczRYlurkuKFE0YhprvKqsARgVa+aWDSI7s6Dgcls
NpSSoH71T4QgxJdcVDNm61Rq7pfDvwfyxrp0Gq2SmCa6RmWC5b/clTTa8jYCieIQ
FhE1CjSq5btE2HC59lma6SicAAFR3EqjEww2qs44YazpBCvndKDPp25btZ7AAHOr
GO5fET/BomJbHXZrKDVJSBD2DgNoglOquKmAAhsi9CC5iDwkejmE1FhdywyALUl/
gJnZxJQZep9JLO/E3l8ML39VoGJ/yelBVRP+MtDJlaV2wU6AOb6Jkt2tCWqoyC50
9giCnqrimFeDXfPTX7PyBHyMPJ+khH7Og24A8R9EFUoec+rlMg+EbtrUOI0CAwEA
AQKCAgBdNVpE3oR2RwIk8dEZPEePI4i+IERtsLy4BAagC1RqxaxDgE84pxfeqhgu
n2Oc1CfRXlpbnIHQuszbZe6VOj7e8eQ9phfWhAWQhmfM8eeO4P8AMLRelvzEDKGL
tDbpywOEk6yAJJaYBWE2lx3ghRQUS7+2x9m9kH2srps2hWWYq2FznsFsx8aUXkwx
4UUkG9ZtZXUfAy+2t1xQupFDio7I58/26ZPJn272+WgvjBA7iY6HLJ3ID+t5f8z5
n0zJmsR6MsG0yTlD9c7LApXbBNT9bVocT4xmBtTSi/5nz9PEoABlsSK90aJnaE66
dOq1ZDagpqqs1L2kPIu2j+X0w02Y6G4uSLdyQML387AZ2UcBQpdSWgIXAJox0pVb
1K8GwgrAqV0sc7m5vGyqOF4jWGM8MZphrRhLCfh8yd85i5zskwsdWsKG35QL43Fx
4TptSJp9ofeIU8hIfzw4gfPDm2NkfZ/V3zgWf4kSLthjtOHQDZpNB1AbzuZH9Tyl
MmCvSQ4aG9mujT7fFGTPuCrPcZLel7V8MWgREzTK0dyg3e8ne9TLF4bC+GalWDnr
dG7kFT44la5mBJJAKmqymEaK36cPYu1fTZ5rGN0NE0Jek1kNsk8qLsv81UZ+kGgI
lKTKHeIXWG9RhZO8GSfkdrsyatKjg2uiS4+Mi2og1SwTMy1EQQKCAQEA/h+vzw0h
vtsg5hVPewkOhKvE1l8S5K8pdl6hME4L6AqVLrwtGnmYlpApRC/uIdWzM+5qKsl9
AOlGBImp6/V+bSbrz5ZJ+40oi1NIn6nwTqp06EJfGHF1rnu5/XnZMR9XuiEDN5XD
jV3KBNzozy7tXIJKsP7/4jjeIJCb8BpNz309EsYgX804Wu+VqNl1yjHli3iX+hl/
as8k2sD6tfKyCJYmBeKVLb7FOJmta2Vzu0rZa9xl5da+mtVdTw5APhOz+j8BJR3j
RBN5zEh9A82YkeSVqcfex2EhJKkbTzghHOM3WtKCNOgKxIYuy1iXTGPOLESZUmZr
c2pxQwBwOUzlxQKCAQEA3NTzMCFgs/iyRe1YdBzfva7nNweeNuyAO0n8TgcOAJJz
oU3GLIKMPghwEiPJvtSjSsPOqp59al+vU+FR96TLMDZl4v/WGOZD0XVBsVj1hJm6
eGi0lgfr++LCUN65lC2TfLU0BhwiUxl6w9UHhEfDudBAnRZz2++ajTBgzGnqhEhE
9sjz7MmLv2dXAUK0JGyEt1CpJYnofJ0Zx0eHAMROnttIw2J37uk1Djn3XfGSi6zX
qOlPF/V+1OxucvrPi/smm6DiMcP/W9ZJ39lUtbw6MOWYmkN7hrMaWn1jac8BpuOd
kTF/QiLY5qOMFM6sx18DG22G0MSnoPYFBtNBUNh8KQKCAQBMXltoPssIXzP40Sis
keEyD6i8v5+e5+Du+Ks6KAo99og0nkpzrV0kyjgMjNbkhiMvlROEvj55uqDXFkPh
bEpNJSgynzimhxpLHIEzsk9MZL9zWRbY8qfqAra3LRoPQBsODYO4/aHh5vCiG30/
Xhvo9CLcJBXj9zER2kNymYUOuNVUwgPSpoqsEVoJfyh91hbknh4WA/mdsJijwODX
MxM7r1vH4vrv32fHha9vGfL4sxq55mcc9jcbsskyy9aUkTlCGBMRA3Vb7PpqYNJp
BS03ktlDR5R0mITsToGtgfG5i7MD8UU9/wnVW3nOlFYLl+bKuObWs37RFYjqGMSh
A7H9AoIBABVVMQT2RHw+SyJ8Mi5NV8PgMI/dWYhewmh31jrHba/adfcgJ0PHfLrF
X+YwtN2NdxTS45UR6HWtNqe4vY1ZyxMmPiN2qX0QSX7jf+wc9uLPYvcczk0sCLz1
g+YCDhVlbbj/XD42244BiR1/59D8icjaeFN0hs65T8nR4Zf9p10OCjN46C94rNpZ
pksF4ZcfMJbw4NYyg1X+ay4YF8+YJywrbNULHyDiQHDWYrIdkxWRJeg4WZ6r5Yu2
J1lOJ1yTb4BbQ16hW3rIsaxBN3Cy9UAh/eLxH+68QJB7Sm4/RB6WIHOVP4DpEuD8
7ZxY9tHvuMIei4aBaNwgyA2HvOiNcTkCggEAf8CtZPJL+Nm+htntttnzZwqxHKlD
lkw7UDVvamxLm5jAHYMQYxAVQh6f82yj6LfxBJ/Ct2hMErGCUqduKyytAxlSG2HL
a/LELfPW0IK1ICIwlFhsIaGou75f+PkezE4IZ7QElfjp7FX2DJrtNbi5+tqapI42
KpzY+hf8rwP+NlKvhbt4Qd7+XGxchW3HUB7o9A0LYLyfLeGbU8FbBLy12USSKnpi
NThibch2+fl3FLMp1In1AnSTeeH/eWIti6+6U61ZMauchMdmesuXfD1qZlat6pl7
SbQU5xzNfKom622EneoVwbFw7rv0n2xFhyFLtK0RiRhGr+Mqcrl8LmK0hA==
-----END RSA PRIVATE KEY----- "
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
