name: Elixir CI

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
    - 'Project.md'
    - 'DeginThinking.md'
    - 'design_thinking/**'

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.7'
        otp-version: '22.3'

    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: time_manager_api/deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Build
      run: docker-compose up -d

    - name: Copy file via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        source: "."
        target: "TimeManager"

    - name: Executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        command_timeout: 15m
        script: |
          ./timemanager.sh
